pipeline {
    agent any
    tools {
          maven 'maven-tool'
    }
    stages {   
        stage ('Git-Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Himanshu-learning/Jenkins-integration-works-Youtube.git'
            }
        }
        
        stage ('Maven-build') {
            steps {
                dir('j2-nexus-jenkins-artifact') {
                                                 sh 'mvn clean package'
                                                 }
                  }
            post {   
                success {  
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
        
        stage ('Nexus-repo') {
            steps {
                  dir('j2-nexus-jenkins-artifact') {
                                           script { 
                                                def mavenPom = readMavenPom file: 'pom.xml'
                                                def nexusRepoName = mavenPom.version.endsWith("SNAPSHOT") ? "nexus-arti-snapshot" : "nexus-arti-release"
                                                nexusArtifactUploader artifacts: [
                                                [artifactId: "${mavenPom.artifactId}", 
                                                classifier: '', 
                                                file: "target/${mavenPom.artifactId}-${mavenPom.version}.${mavenPom.version}", 
                                                type: "${mavenPom.packaging}"
                                                ]
                                                  ], 
                                                  credentialsId: 'nexus-cred', 
                                                  groupId: "${mavenPom.groupId}" , 
                                                  nexusUrl: "${env.nexus_ip}", 
                                                  nexusVersion: 'nexus3', 
                                                  protocol: 'http', 
                                                  repository: "${nexusRepoName}" , 
                                                  version: "${mavenPom.version}"
                                                 }
                }
            }
        }
    }
}
