pipeline {
    agent any
    tools {
          sh 'maven-tool'
    }
    stages {   
        stage ('Git-Checkout') {
            steps {
                git branch: 'main',
                credentialsId: '',
                url: 'https://github.com/Himanshu-learning/Jenkins-integration-works-Youtube.git'
            }
        }
        
        stage ('Maven-build') {
            steps {
                dir('j2-nexus-jenkins-artifact') {
                                                 sh 'mvn clean package'
                                                 }
                  }
            post {   
                success {  
                    archiveArtifacts artifacts: '**/*.jar'
                }
            }
        }
        

    }
}
