pipeline {
   agent any 
   
   tools {
      maven 'maven-tool'
   }
   
   stages {
      stage('Git-checkout') {
	    steps {
	           git branch: 'main', url: 'https://github.com/Himanshu-learning/Jenkins-integration-works-Youtube.git'
		}
	  }
	  stage('Build') {
	    steps {
                  dir('j1-sonarqube-jenkins') {
                                              sh 'mvn clean package'
                                              }
		  } 
	  }
	  stage('Sonarqube-Analysis') {
	      steps {
		     dir('j1-sonarqube-jenkins') { 
		                                 withSonarQubeEnv('sonar-server') {
				                                                   sh 'mvn sonar:sonar'
			                                                          }
		                                 } 
	            }
        }
    }
    post {
          always {
	         deleteDir()
	         }
         }
}
